// ---------------------------------------------------------------------------
// AI Horde image generation — FREE, crowdsourced Stable Diffusion workers.
//
// Verified against the live API (v5.1.11) before implementing:
//   POST /api/v2/generate/async     → { id, kudos }
//   GET  /api/v2/generate/check/:id → { done, faulted, waiting, processing,
//                                       queue_position, wait_time, is_possible }
//   GET  /api/v2/generate/status/:id→ { generations: [{ img, model, worker_name,
//                                       state }] }  (img = R2 URL when r2:true)
//   GET  /api/v2/status/models?type=image → live worker/model list
//
// Anonymous access works with the documented shared key "0000000000" (verified:
// a real 512×512 image came back in ~5s). Supplying AI_HORDE_API_KEY gives the
// account's own kudos priority — strongly recommended, still free.
//
// The key is read from the server environment only and never reaches the
// browser. Generated bytes are downloaded server-side and handed to the caller.
// ---------------------------------------------------------------------------

import { logEvent } from "@/lib/http";
import type { FailureCategory } from "@/lib/openrouter";

const BASE_URL = (process.env.AI_HORDE_BASE_URL ?? "https://aihorde.net/api/v2").replace(
  /\/$/,
  ""
);

/** Documented shared anonymous key. Lowest queue priority but genuinely free. */
export const ANONYMOUS_KEY = "0000000000";

/** Widely-hosted default: most workers, shortest queue at time of writing. */
export const DEFAULT_HORDE_MODEL = "stable_diffusion";

export function hordeApiKey(): string {
  return process.env.AI_HORDE_API_KEY?.trim() || ANONYMOUS_KEY;
}

export function usingAnonymousKey(): boolean {
  return hordeApiKey() === ANONYMOUS_KEY;
}

export function hordeModel(): string {
  return (process.env.AI_HORDE_MODEL ?? DEFAULT_HORDE_MODEL).trim() || DEFAULT_HORDE_MODEL;
}

/** AI Horde needs no credits — it is always available as a generation backend. */
export function imageGenConfigured(): boolean {
  return true;
}

function headers(): Record<string, string> {
  return {
    apikey: hordeApiKey(),
    "Content-Type": "application/json",
    // The API asks clients to identify themselves.
    "Client-Agent": "aura-personal-ai:1.0:github.com/aw0809008-ui/my-ai-agent",
  };
}

export class HordeError extends Error {
  category: FailureCategory;
  status: number | null;
  constructor(message: string, status: number | null, category: FailureCategory) {
    super(message);
    this.status = status;
    this.category = category;
  }
}

function categorise(status: number | null): FailureCategory {
  if (status === null) return "network";
  if (status === 401 || status === 403) return "auth";
  if (status === 429) return "rate_limited";
  if (status === 404) return "not_found";
  if (status === 400 || status === 422) return "unsupported";
  if (status >= 500) return "upstream";
  return "unknown";
}

export interface GeneratedImage {
  bytes: Buffer;
  mime: string;
  modelId: string;
  modelName: string;
}

export interface HordeProgress {
  /** queue position, or null while processing */
  queuePosition: number | null;
  waitSeconds: number | null;
  processing: number;
  finished: number;
}

const ALLOWED_MIME = new Set(["image/png", "image/jpeg", "image/webp"]);

/** Trust magic bytes over any advertised content-type. */
function sniffMime(buf: Buffer): string | null {
  if (
    buf.length > 8 &&
    buf.subarray(0, 8).equals(Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]))
  )
    return "image/png";
  if (buf.length > 3 && buf[0] === 0xff && buf[1] === 0xd8 && buf[2] === 0xff) return "image/jpeg";
  if (
    buf.length > 12 &&
    buf.subarray(0, 4).toString("ascii") === "RIFF" &&
    buf.subarray(8, 12).toString("ascii") === "WEBP"
  )
    return "image/webp";
  return null;
}

/** Read declared pixel dimensions so we can reject 0×0 / corrupt payloads. */
function imageDimensions(buf: Buffer, mime: string): { w: number; h: number } | null {
  try {
    if (mime === "image/png" && buf.length > 24)
      return { w: buf.readUInt32BE(16), h: buf.readUInt32BE(20) };
    if (mime === "image/webp" && buf.length > 30) {
      const fourcc = buf.subarray(12, 16).toString("ascii");
      if (fourcc === "VP8X") return { w: (buf.readUIntLE(24, 3) & 0xffffff) + 1, h: (buf.readUIntLE(27, 3) & 0xffffff) + 1 };
      if (fourcc === "VP8L") {
        const b = buf.readUInt32LE(21);
        return { w: (b & 0x3fff) + 1, h: ((b >> 14) & 0x3fff) + 1 };
      }
      if (fourcc === "VP8 ")
        return { w: buf.readUInt16LE(26) & 0x3fff, h: buf.readUInt16LE(28) & 0x3fff };
      return null; // unknown webp variant: don't fail on dimension check alone
    }
    if (mime === "image/jpeg") {
      let i = 2;
      while (i + 9 < buf.length) {
        if (buf[i] !== 0xff) {
          i++;
          continue;
        }
        const marker = buf[i + 1];
        if (marker >= 0xc0 && marker <= 0xcf && marker !== 0xc4 && marker !== 0xc8 && marker !== 0xcc)
          return { h: buf.readUInt16BE(i + 5), w: buf.readUInt16BE(i + 7) };
        i += 2 + buf.readUInt16BE(i + 2);
      }
    }
  } catch {
    return null;
  }
  return null;
}

interface SubmitResponse {
  id?: string;
  kudos?: number;
  message?: string;
  errors?: Record<string, string>;
}

interface CheckResponse {
  done?: boolean;
  faulted?: boolean;
  waiting?: number;
  processing?: number;
  finished?: number;
  queue_position?: number;
  wait_time?: number;
  is_possible?: boolean;
  message?: string;
}

interface StatusResponse {
  done?: boolean;
  faulted?: boolean;
  generations?: {
    img?: string;
    model?: string;
    worker_name?: string;
    state?: string;
    censored?: boolean;
  }[];
  message?: string;
}

async function hordeFetch<T>(
  path: string,
  init: RequestInit & { timeoutMs?: number } = {}
): Promise<T> {
  const { timeoutMs = 20_000, ...rest } = init;
  let res: Response;
  try {
    res = await fetch(`${BASE_URL}${path}`, {
      ...rest,
      headers: { ...headers(), ...(rest.headers ?? {}) },
      signal: AbortSignal.timeout(timeoutMs),
    });
  } catch (e) {
    throw new HordeError(
      e instanceof Error ? e.message.slice(0, 160) : "network failure",
      null,
      "network"
    );
  }
  const text = await res.text();
  let json: unknown = null;
  try {
    json = text ? JSON.parse(text) : null;
  } catch {
    if (!res.ok)
      throw new HordeError(`AI Horde error ${res.status}`, res.status, categorise(res.status));
    throw new HordeError("malformed AI Horde response", res.status, "unknown");
  }
  if (!res.ok) {
    const j = json as { message?: string; errors?: Record<string, string> };
    const detail =
      j?.message ??
      (j?.errors ? Object.values(j.errors).join("; ") : "") ??
      `error ${res.status}`;
    throw new HordeError(String(detail).slice(0, 220), res.status, categorise(res.status));
  }
  return json as T;
}

export interface GenerateOptions {
  width?: number;
  height?: number;
  steps?: number;
  /** hard cap on total wait; polling stops after this */
  timeoutMs?: number;
  /** user pressed Stop → abort polling promptly */
  signal?: AbortSignal;
  /** progress callback for chat status lines */
  onProgress?: (p: HordeProgress) => void;
}

/** Round to the multiple of 64 the Horde API requires. */
function snap(n: number, min: number, max: number): number {
  const v = Math.round(n / 64) * 64;
  return Math.max(min, Math.min(max, v));
}

/**
 * Submit a job, poll until done, download and validate the image.
 * Never returns a placeholder — failures throw HordeError with a real category.
 */
export async function generateImage(
  prompt: string,
  opts: GenerateOptions = {}
): Promise<GeneratedImage> {
  try {
    return await runGeneration(prompt, opts);
  } catch (e) {
    noteImageError(e instanceof HordeError ? e.category : "unknown");
    throw e;
  }
}

async function runGeneration(
  prompt: string,
  opts: GenerateOptions
): Promise<GeneratedImage> {
  const model = hordeModel();
  const width = snap(opts.width ?? 512, 64, 1024);
  const height = snap(opts.height ?? 512, 64, 1024);
  const timeoutMs = opts.timeoutMs ?? 150_000;
  const started = Date.now();

  const submit = await hordeFetch<SubmitResponse>("/generate/async", {
    method: "POST",
    timeoutMs: 25_000,
    body: JSON.stringify({
      prompt: prompt.slice(0, 1000),
      params: {
        width,
        height,
        steps: Math.min(Math.max(opts.steps ?? 20, 10), 30),
        n: 1,
        sampler_name: "k_euler",
        cfg_scale: 7,
      },
      models: [model],
      nsfw: false,
      censor_nsfw: true,
      // ask for an R2 URL instead of inline base64 (smaller responses)
      r2: true,
      trusted_workers: false,
    }),
  });

  const id = submit.id;
  if (!id) throw new HordeError("AI Horde did not return a job id", null, "empty");

  logEvent({ msg: "horde_submitted", model, anonymous: usingAnonymousKey(), width, height });

  // ---- bounded polling: 2s → 5s backoff, hard timeout, abortable ----------
  let delay = 2000;
  let lastProgress: HordeProgress | null = null;
  for (;;) {
    if (opts.signal?.aborted) {
      // best-effort cancel so a worker isn't left generating for nobody
      void hordeFetch(`/generate/status/${id}`, { method: "DELETE", timeoutMs: 8000 }).catch(
        () => {}
      );
      throw new HordeError("generation cancelled", null, "unknown");
    }
    if (Date.now() - started > timeoutMs) {
      void hordeFetch(`/generate/status/${id}`, { method: "DELETE", timeoutMs: 8000 }).catch(
        () => {}
      );
      const pos = lastProgress?.queuePosition;
      const eta = lastProgress?.waitSeconds;
      throw new HordeError(
        `still waiting after ${Math.round(timeoutMs / 1000)}s` +
          (pos ? ` — position #${pos} in the shared queue` : "") +
          (eta && eta > 60 ? `, estimated ~${Math.round(eta / 60)} min` : ""),
        null,
        "rate_limited"
      );
    }

    const check = await hordeFetch<CheckResponse>(`/generate/check/${id}`, { timeoutMs: 15_000 });

    if (check.faulted)
      throw new HordeError("the worker failed to complete this generation", null, "upstream");
    if (check.is_possible === false)
      throw new HordeError(
        `no available worker can serve model "${model}" right now`,
        null,
        "not_found"
      );

    lastProgress = {
      queuePosition: check.queue_position ?? null,
      waitSeconds: check.wait_time ?? null,
      processing: check.processing ?? 0,
      finished: check.finished ?? 0,
    };
    opts.onProgress?.(lastProgress);

    if (check.done) break;

    // Fail fast when the queue reports a wait far beyond our budget instead of
    // holding the request open pointlessly — the user gets a real ETA now.
    const remainingMs = timeoutMs - (Date.now() - started);
    if (
      lastProgress.waitSeconds !== null &&
      lastProgress.waitSeconds * 1000 > remainingMs * 2 &&
      Date.now() - started > 15_000
    ) {
      void hordeFetch(`/generate/status/${id}`, { method: "DELETE", timeoutMs: 8000 }).catch(
        () => {}
      );
      throw new HordeError(
        `the shared queue is busy — position #${lastProgress.queuePosition ?? "?"}, estimated ~${Math.round(
          lastProgress.waitSeconds / 60
        )} min`,
        null,
        "rate_limited"
      );
    }

    await new Promise((r) => setTimeout(r, delay));
    delay = Math.min(delay + 1000, 5000);
  }

  const status = await hordeFetch<StatusResponse>(`/generate/status/${id}`, { timeoutMs: 20_000 });
  if (status.faulted)
    throw new HordeError("the generation faulted before completing", null, "upstream");

  const gen = status.generations?.find((g) => g.img);
  if (!gen?.img) throw new HordeError("AI Horde returned no image", null, "empty");

  // ---- download (R2 URL) or decode inline base64 --------------------------
  let bytes: Buffer;
  if (/^https?:\/\//.test(gen.img)) {
    let res: Response;
    try {
      res = await fetch(gen.img, { signal: AbortSignal.timeout(30_000) });
    } catch (e) {
      throw new HordeError(
        e instanceof Error ? `image download failed: ${e.message.slice(0, 120)}` : "download failed",
        null,
        "network"
      );
    }
    if (!res.ok)
      throw new HordeError(`image download failed (${res.status})`, res.status, "upstream");
    bytes = Buffer.from(await res.arrayBuffer());
  } else {
    try {
      bytes = Buffer.from(gen.img, "base64");
    } catch {
      throw new HordeError("undecodable image payload", null, "unknown");
    }
  }

  // ---- validation: real bytes, allowed type, sane dimensions -------------
  if (bytes.length < 512) throw new HordeError("image payload was empty", null, "empty");
  const mime = sniffMime(bytes);
  if (!mime || !ALLOWED_MIME.has(mime))
    throw new HordeError("unsupported image format returned", null, "unsupported");
  const dims = imageDimensions(bytes, mime);
  if (dims && (dims.w < 32 || dims.h < 32 || dims.w > 4096 || dims.h > 4096))
    throw new HordeError(`invalid image dimensions (${dims.w}×${dims.h})`, null, "unsupported");

  logEvent({
    msg: "horde_ok",
    model: gen.model ?? model,
    bytes: bytes.length,
    mime,
    ms: Date.now() - started,
    anonymous: usingAnonymousKey(),
  });

  return {
    bytes,
    mime,
    modelId: gen.model ?? model,
    modelName: `AI Horde · ${gen.model ?? model}`,
  };
}

// ---------------------------------------------------------------------------
// Diagnostics
// ---------------------------------------------------------------------------

export interface HordeHealth {
  provider: "ai-horde";
  configured: boolean;
  anonymous: boolean;
  reachable: boolean;
  model: string;
  modelWorkers: number | null;
  queueEtaSeconds: number | null;
  note: string;
}

let healthCache: { at: number; value: HordeHealth | null } = { at: 0, value: null };

/** Last safe failure category, for admin diagnostics (no prompt content). */
let lastErrorCategory: FailureCategory | null = null;
export function lastImageErrorCategory(): FailureCategory | null {
  return lastErrorCategory;
}
export function noteImageError(c: FailureCategory): void {
  lastErrorCategory = c;
}

export async function hordeHealth(): Promise<HordeHealth> {
  if (healthCache.value && Date.now() - healthCache.at < 60_000) return healthCache.value;
  const model = hordeModel();
  const base: HordeHealth = {
    provider: "ai-horde",
    configured: true,
    anonymous: usingAnonymousKey(),
    reachable: false,
    model,
    modelWorkers: null,
    queueEtaSeconds: null,
    note: usingAnonymousKey()
      ? "Using the shared anonymous key — free but lowest queue priority. Set AI_HORDE_API_KEY for faster generations."
      : "Using a personal AI Horde key.",
  };
  try {
    const models = await hordeFetch<{ name?: string; count?: number; eta?: number }[]>(
      "/status/models?type=image",
      { timeoutMs: 10_000 }
    );
    const entry = models.find((m) => m.name === model);
    healthCache = {
      at: Date.now(),
      value: {
        ...base,
        reachable: true,
        modelWorkers: entry?.count ?? 0,
        queueEtaSeconds: entry?.eta ?? null,
        note:
          entry === undefined
            ? `Model "${model}" is not currently served by any worker — set AI_HORDE_MODEL to an available one.`
            : base.note,
      },
    };
  } catch {
    healthCache = { at: Date.now(), value: base };
  }
  return healthCache.value!;
}
